# This file is included via the manifest
include:
  - git: https://github.com/ACCESS-NRI/access-spack-packages
    # FIXME: Remove after merging into api-v2
    branch: 484-top-level-includes
    paths:
    - .github/build-ci/include/ci
