# This file is included via the manifest
# It has two variations on the include:
# For CRs (which don't have vars.USE_CALLER_REPOSITORY_PATH set): They use this repos .github/build-ci/include/local
# For ASP (which do have the above var set): Use the $CALLER_REPOSITORY_PATH_CONFIG path to include instead, which is set in build-ci to be the caller ASP
include:
  - path: $CALLER_REPOSITORY_PATH_CONFIG
    when: "'USE_CALLER_REPOSITORY_PATH' in env"
  - git: https://github.com/ACCESS-NRI/access-spack-packages
    branch: 484-top-level-includes
    paths:
    - .github/build-ci/include/base
    when: "'USE_CALLER_REPOSITORY_PATH' not in env"
